name: Daily Readme Update

on:
  schedule:
    - cron: "10 13 * * *"
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Random Quote and Update README
        run: |
          # Fetch random quote from API
          QUOTE_DATA=$(curl -s "https://api.quotable.io/random")
          QUOTE=$(echo "$QUOTE_DATA" | jq -r '.content')
          AUTHOR=$(echo "$QUOTE_DATA" | jq -r '.author')
          
          # Update README with new quote
          sed -i '/<!-- QUOTE:START -->/,/<!-- QUOTE:END -->/c\<!-- QUOTE:START -->\n> "'"$QUOTE"'"\n> \n> â€” *'"$AUTHOR"'*\n<!-- QUOTE:END -->' README.md
          
          git config --global user.email "anujshrivastava10e@gmail.com"
          git config --global user.name "Anuj"
          git add README.md
          git diff --staged --quiet || git commit -m "ðŸ“œ Daily Quote Update - $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M')"
          git push origin main || true